### ISSUE TITLE
Failed to compile Fakesu app

### ISSUE THREAD

**Issue by vikassy** [fabiokung/heroku-buildpack-fakesu#1] opened 2013-03-08 23:10 UTC
Hello, 
Your documentation is awesome, but I have come across a problem. When I follow those methods I get 

-----> Fetching custom git buildpack... done
-----> fakesu app detected
-----> Fetching and installing wget
       wget installed
-----> Fetching and installing debootstrap
 !     Heroku push rejected, failed to compile Fakesu app

**Comment by mfagundes** [comment] 2013-03-14 18:05
Same problem here. Any thoughts?

**Comment by fabiokung** [comment] 2013-03-15 04:25
I can reproduce it and will dig into as soon as possible (which may take a while, unfortunately).

**Comment by msakrejda** [comment] 2013-07-17 03:34
It looks like this may be because [that version](https://github.com/fabiokung/heroku-buildpack-fakesu/blob/master/bin/compile#L46) of debootstrap is [no longer available](http://archive.ubuntu.com/ubuntu/pool/main/d/debootstrap/). I'm doing some digging in my copious spare time, and may or may not get further...

**Comment by msakrejda** [comment] 2013-07-17 03:48
Actually, it looks like a couple of the other buildpacks in the network are further ahead; I'm going to see where I can get with some of those first.

**Comment by pouya314** [comment] 2013-12-12 09:21
any updates on this issue? I'm having the same problem.

**Comment by fabiokung** [comment] 2013-12-24 17:45
Closed by #2.

**Closed as completed by fabiokung** 2013-12-24 17:45 UTC
